name: Build Binaries

run-name: Running perf test for ${{ inputs.chosen-runner }}
on:
  workflow_dispatch:
    inputs:
      chosen-runner:
        required: true
        type: choice
        options:
        - alex-arm64-linux
        - alex-arm64-windows
        - 4-core-ubuntu-benchmark-perf-test
        - 8-core-windows-benchmark-perf-test

env:
  GO_VERSION: '1.20'
  CGO_ENABLED: 0
  IN_DOCKER: ""

jobs:

  build-webui:
    runs-on: ${{ inputs.chosen-runner }}

    steps:
      - name: Install make
        run: sudo apt-get install -y make
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build webui
        run: |
          make clean-webui generate-webui
          tar czvf webui.tar.gz ./webui/static/

      - name: Artifact webui
        uses: actions/upload-artifact@v3
        with:
          name: webui.tar.gz
          path: webui.tar.gz

  build:
    runs-on: ${{ inputs.chosen-runner }}
    needs:
      - build-webui
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/traefik/traefik

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/traefik/traefik
          fetch-depth: 0

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            '%LocalAppData%\go-build'
          key: ${{ runner.os }}-build-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-go-

      - name: Artifact webui
        uses: actions/download-artifact@v3
        with:
          name: webui.tar.gz
          path: ${{ github.workspace }}/go/src/github.com/traefik/traefik

      - name: Untar webui
        run: tar xvf webui.tar.gz

      - name: Build
        run: make binary
